language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.4
  - 3.3
  - 3.2

install:
  - pip install "pip>=7.1.0"
  - pip install -r dev-requirements.txt
  - python setup.py install
script: ./run_tests.sh
