language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.5
  - 3.4
  - 3.3
  - pypy3

env:
  global:
    - TEST_DB_HOST=localhost
    - TEST_MYSQL_USER=root
    - TEST_POSTGRES_USER=postgres

install:
  - pip install "pip>=8.0.0"
  - pip install -r dev-requirements.txt
  - python setup.py install

script:
  - coverage run -m unittest openid.test.test_suite
  - coverage report

after_success:
  - coveralls
